USE CFB;


CREATE TABLE USER_TAB (USERID VARCHAR(15) PRIMARY KEY, NAME VARCHAR(15), CONTACT_NO VARCHAR(15), PASSWORD VARCHAR(15), DEPARTMENT VARCHAR(15), TYPE INT, BRANCH_NAME VARCHAR(15),EMAILID VARCHAR
(30));
INSERT INTO USER_TAB VALUES ('12345', 'M&M', '900001000','ABCD@1234','CIT',0,'OSS','ABCD@GMAIL.COM');
SELECT * FROM USER_TAB;

CREATE TABLE COURSE_TAB (COURSE_CODE VARCHAR(15) PRIMARY KEY, COURSE_TITLE VARCHAR(30), ALLOTTED_TO VARCHAR(15), FOREIGN KEY(ALLOTTED_TO) REFERENCES USER_TAB(USERID), SEMESTER VARCHAR(15),COURSE VARCHAR(10));
INSERT INTO COURSE_TAB VALUES ('123', 'compiler design', '12345','fifth','OSS');
SELECT * FROM COURSE_TAB;


CREATE TABLE COURSE_PROGRESS_TAB (USER VARCHAR(15), FOREIGN KEY(USER) REFERENCES USER_TAB(USERID), COURSE VARCHAR(15),MONTH VARCHAR(15), NO_OF_LECTURES_TAKEN INT, PERC_SYLLABUS_COVERED INT, NO_OF_ASSIGNMENT INT, NO_OF_TEST VARCHAR(10), NO_OF_QUIZ VARCHAR(10));
INSERT INTO COURSE_PROGRESS_TAB VALUES ('12345','OSS','Jan',5,50,4,3,2);
SELECT * FROM COURSE_PROGRESS_TAB;

CREATE TABLE COURSE_DIARY (USER VARCHAR(15), FOREIGN KEY(USER) REFERENCES USER_TAB(USERID), COURSE VARCHAR(15),DATE_OF_LECTURE VARCHAR(15), TOPICS_COVERED VARCHAR(20), LECTURE_NO INT, PLAN_DATE VARCHAR(10), REMARKS VARCHAR(25));
INSERT INTO COURSE_DIARY VALUES ('12345','compiler design','Jan 9,2017','LL1 Parsing',5,'Jan 7,2017','Damn!');
SELECT * FROM COURSE_DIARY;


CREATE TABLE TIMETABLE_TAB (USER VARCHAR(15), FOREIGN KEY(USER) REFERENCES USER_TAB(USERID), START_TIME VARCHAR(15), END_TIME VARCHAR(15) , DESCRIPTION VARCHAR(25));
INSERT INTO TIMETABLE_TAB VALUES ('12345', '9:30', '10:30','Computer Graphics');
SELECT * FROM TIMETABLE_TAB;

CREATE TABLE FILE_TAB (FILE_TYPE VARCHAR(15), UPLOADED_BY VARCHAR(15), FOREIGN KEY(UPLOADED_BY) REFERENCES USER_TAB(USERID), COURSE_CODE VARCHAR(15), FOREIGN KEY(COURSE_CODE) REFERENCES COURSE_TAB(COURSE_CODE) , DATE_OF_UPLOAD VARCHAR(15), TIME_OF_UPLOAD VARCHAR(20), BRANCH VARCHAR(10), FILE_ADDRESS VARCHAR(45));
INSERT INTO FILE_TAB VALUES ('PDF','12345','123','9/10','9:30','oss','localhost/files/user/abcd.pdf');
SELECT * FROM FILE_TAB;
